#!/bin/sh

IMAGE=codercom/code-server:latest
DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
cd ${DIR}/..
docker pull node:latest
docker pull mozilla/sbt:latest
docker pull ${IMAGE}
docker build -t novsyama/code-server-sbt \
 --build-arg VCS_REF=`git rev-parse --short HEAD` \
 --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
 .
docker tag novsyama/code-server-sbt novsyama/code-server-sbt:local
docker images novsyama/code-server-sbt

